package appligds;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author boqui
 */
public class AppliGDS1 extends javax.swing.JFrame {

    /**
     * Creates new form AppliGDS1
     */
    
    private DefaultTableModel dt;
    private int id;
    private String nom,prenom,sexe;
    private String service,nmagasin;
    private String dure;
    
    private int i; // un indice de déplacement
    
    private Statement st;
    private ResultSet rs;
   
    public AppliGDS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnmagasin = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtduree = new javax.swing.JTextField();
        combservice = new javax.swing.JComboBox<>();
        jrb1 = new javax.swing.JCheckBox();
        jrb2 = new javax.swing.JCheckBox();
        jrb3 = new javax.swing.JCheckBox();
        btnn1 = new javax.swing.JButton();
        btnn5 = new javax.swing.JButton();
        btnn3 = new javax.swing.JButton();
        btnn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstg = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        comborech = new javax.swing.JComboBox<>();
        txtrech = new javax.swing.JTextField();
        btnn4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        btnpremier = new javax.swing.JButton();
        btnprecedent = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(980, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("id :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("nmagasin :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("nom :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("prenom :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("service :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("dstage :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("sexe :");

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtnmagasin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtduree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        combservice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gestion des jeux ", "gestion des stocks", "assistance client", "gestion finance et fiscale", "livraison", "gestion des recrutement" }));

        jrb1.setText("Masculin");
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });

        jrb2.setText("Féminin");
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });

        jrb3.setText("Autre");
        jrb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb3ActionPerformed(evt);
            }
        });

        btnn1.setBackground(new java.awt.Color(255, 204, 51));
        btnn1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnn1.setText("AJOUTER");
        btnn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn1MouseExited(evt);
            }
        });
        btnn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn1ActionPerformed(evt);
            }
        });

        btnn5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnn5.setText("RECHERCHER");
        btnn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn5MouseExited(evt);
            }
        });
        btnn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn5ActionPerformed(evt);
            }
        });

        btnn3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnn3.setText("SUPPRIMER");
        btnn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn3MouseExited(evt);
            }
        });
        btnn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn3ActionPerformed(evt);
            }
        });

        btnn2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnn2.setText("MODIFIER");
        btnn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn2MouseExited(evt);
            }
        });
        btnn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn2ActionPerformed(evt);
            }
        });

        tblstg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblstg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstg);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("recherche par :");

        comborech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "nmagasin", "nom", "prenom", "service", "dstage", "sexe" }));
        comborech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comborechActionPerformed(evt);
            }
        });

        txtrech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrech.setForeground(new java.awt.Color(255, 204, 0));

        btnn4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnn4.setText("ACTUALISER");
        btnn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn4MouseExited(evt);
            }
        });
        btnn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn4ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\boqui\\Desktop\\VD15\\Capture.PNG")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jbtnExit.setText("Quitter!");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        btnpremier.setText("premier");
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });

        btnprecedent.setText("precedent");
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });

        btnsuivant.setText("suivant");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });

        btndernier.setText("dernier");
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnmagasin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtduree, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtprenom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combservice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(59, 59, 59)
                                .addComponent(jrb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb3)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnn1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnn2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnn3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnn4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnpremier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnprecedent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsuivant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndernier)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnExit))
                            .addComponent(txtrech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comborech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtnmagasin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(combservice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtduree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrb2)
                                .addComponent(jrb3)
                                .addComponent(jrb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnpremier)
                            .addComponent(btnprecedent)
                            .addComponent(btnsuivant)
                            .addComponent(btndernier)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comborech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnExit)
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
sexe=jrb1.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jrb1ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
sexe=jrb2.getText();         // TODO add your handling code here:
    }//GEN-LAST:event_jrb2ActionPerformed

    private void jrb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb3ActionPerformed
sexe=jrb3.getText();         // TODO add your handling code here:
    }//GEN-LAST:event_jrb3ActionPerformed

    private void btnn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn5ActionPerformed
try{
    String sql = "SELECT * FROM stagaire WHERE ";
    dt.setRowCount(0);
    Statement st = AppliGDS.getConnection().createStatement();
        ResultSet rs = st.executeQuery(sql +combo()
            +" like '%"+txtrech.getText()+"%'");
    
    while(rs.next()){
        id=rs.getInt(1);
        nmagasin = rs.getString("nmagasin");
        nom = rs.getString(3);
        prenom = rs.getString(4);
        service = rs.getString(5);
        dure = rs.getString(6);
        sexe = rs.getString(7);
        
        Object[] stg = {id,nmagasin,nom,prenom,service,dure,sexe};
        dt.addRow(stg);
    }
    
    if (dt.getRowCount() == 0){
        JOptionPane.showMessageDialog(null, "Aucun Stagiaire corespondant");
        Afficher();
    }else{
        i = 0;
        Deplacer(i);
    }
    
}catch (HeadlessException | SQLException m){JOptionPane.showMessageDialog(null, ""+m.getMessage());
System.err.println(m);}
// TODO add your handling code here:
    }//GEN-LAST:event_btnn5ActionPerformed

    private void btnn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn2ActionPerformed
try{
    if (JOptionPane.showConfirmDialog(null,"confirmer la modification","modification du stagiaire",
            JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
        String sql = "UPDATE stagaire SET nmagasin='"+txtnmagasin.getText()+"',nom='"+txtnom.getText()
                        +"',prenom='"+txtprenom.getText()+"',service='"+combservice.getSelectedItem().toString()
                        +"',dstage ='"+txtduree.getText()+"',sexe='"+sexe
                        +"' WHERE id = "+ txtid.getText();
        PreparedStatement ps;
        ps = AppliGDS.getConnection().prepareStatement(sql);
        ps.executeUpdate();
        Afficher();
    }
}catch( HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnn2ActionPerformed

    private void comborechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comborechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comborechActionPerformed

    private void btnn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn4ActionPerformed
actualiser();
Afficher();
// TODO add your handling code here:
    }//GEN-LAST:event_btnn4ActionPerformed

    private void btnn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnn1MouseClicked

    private void btnn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseEntered
btnn1.setBackground(new java.awt.Color(255,204,51));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn1MouseEntered

    private void btnn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseExited
btnn1.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn1MouseExited

    private void btnn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn2MouseEntered
btnn2.setBackground(new java.awt.Color(255,204,51));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn2MouseEntered

    private void btnn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn2MouseExited
btnn2.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn2MouseExited

    private void btnn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn3MouseEntered
btnn3.setBackground(new java.awt.Color(255,204,51));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn3MouseEntered

    private void btnn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn3MouseExited
btnn3.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn3MouseExited

    private void btnn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn4MouseEntered
btnn4.setBackground(new java.awt.Color(255,204,51));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn4MouseEntered

    private void btnn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn4MouseExited
btnn4.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn4MouseExited

    private void btnn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn5MouseEntered
btnn5.setBackground(new java.awt.Color(255,204,51));         // TODO add your handling code here:
    }//GEN-LAST:event_btnn5MouseEntered

    private void btnn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn5MouseExited
btnn5.setBackground(new java.awt.Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn5MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
        
        st = (Statement) AppliGDS.getConnection().createStatement();
        
        jrbg.add(jrb1);
        jrbg.add(jrb2);
        jrbg.add(jrb3);
        
        dt = new DefaultTableModel();// dt est une variable qui est pour stocké les elements d'un tableau (lignes et colonnes)
        
        dt.addColumn("id");
        dt.addColumn("nmagasin");
        dt.addColumn("nom");
        dt.addColumn("prenom");
        dt.addColumn("service");
        dt.addColumn("duree");
        dt.addColumn("sexe");
        tblstg.setModel(dt);
        
          Afficher();
          
          i = 0;
          Deplacer(i);
        }catch (SQLException e) {
            System.out.printf("erreur "+e.getMessage());
            JOptionPane.showMessageDialog(null, "Erreur de connexion\n "+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tblstgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstgMouseClicked
try{
    i = tblstg.getSelectedRow(); // retourne la ligne sélectionner par l'user
    
    Deplacer(i);
}catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnée stg\n"+e.getMessage());
        }   // TODO add your handling code here:
    }//GEN-LAST:event_tblstgMouseClicked

    private void btnn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn1ActionPerformed
try{
    
    String sql = "INSERT INTO stagaire (nmagasin,nom,prenom,service,dstage,sexe)VALUES (?,?,?,?,?,?)";
    PreparedStatement ps;
    ps = AppliGDS.getConnection().prepareStatement(sql);
    ps.setString(1,txtnmagasin.getText());
    ps.setString(2,txtnom.getText());
    ps.setString(3,txtprenom.getText());
    ps.setString(4,combservice.getSelectedItem().toString());
    ps.setString(5,txtduree.getText());
    ps.setString(6,sexe);
    
    ps.executeUpdate();
    Afficher();
        JOptionPane.showMessageDialog(null, "Stagiaire ajouté à la liste");  
}catch( HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(null, "Erreur identifié lors de l'insertion stg\n"+e.getMessage());
    System.err.println(""+e.getMessage());
}

// TODO add your handling code here:
    }//GEN-LAST:event_btnn1ActionPerformed

    private void btnn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn3ActionPerformed
try{
    if(JOptionPane.showConfirmDialog(null,"Attention cette action est irréverssible!"
    +"Poursuivre?","Supression avec succès du stagiaire selectionner",JOptionPane.YES_NO_OPTION) 
            == JOptionPane.OK_OPTION){
        String sql = "Delete from stagaire where id = ";
        PreparedStatement ps;
        ps = AppliGDS.getConnection().prepareStatement(sql);
        ps.executeUpdate( sql + txtid.getText());
        Afficher();
    }
    
}catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(null, "Erreur survenue lors de la suppression stg !\n"+e.getMessage());
}   

// TODO add your handling code here:
    }//GEN-LAST:event_btnn3ActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
premier();        // TODO add your handling code here:
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
precedent();        // TODO add your handling code here:
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
suivant();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
dernier();        // TODO add your handling code here:
    }//GEN-LAST:event_btndernierActionPerformed

String combo(){
    switch(comborech.getSelectedIndex()){
        case 0: return "id";
        case 1: return "nmagasin";
        case 2: return "nom";
        case 3: return "prenom";
        case 4: return "service";
        case 5: return "dstage";
        case 6: return "sexe";
    }
    return "";
}
    
    
private void Afficher(){
    
    txtid.setEnabled(false);
    
        try{
            String sql = "Select * from stagaire";
            dt.setRowCount(0);
            
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                id = rs.getInt("id");
                nmagasin = rs.getString("nmagasin");
                nom = rs.getString("nom");
                prenom = rs.getString("prenom");
                service = rs.getString("service");
                dure = rs.getString("dstage");
                sexe = rs.getString("sexe");
                Object[] t = {id,nmagasin,nom,prenom,service,dure,sexe};
                dt.addRow(t);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Erreur afficher dans la liste des stagiaires "+e.getMessage());
        } 
}

private void Deplacer(int i){
    try{
       if (dt.getRowCount() == 0){//
            btnprecedent.setEnabled(false);
            btnsuivant.setEnabled(false);
            actualiser();
        }else{
            if(i == 0){
                btnprecedent.setEnabled(false);
                btnsuivant.setEnabled(true);
            }else if(i == dt.getRowCount()-1){//
                btnprecedent.setEnabled(true);
                btnsuivant.setEnabled(false);
            }else{
                btnprecedent.setEnabled(true);
                btnsuivant.setEnabled(true);
            }
            if(dt.getRowCount() == 1){//
                btnprecedent.setEnabled(false);
                btnsuivant.setEnabled(false);
                btnpremier.setEnabled(false);
                btndernier.setEnabled(false);
            }else{
                btnpremier.setEnabled(true);
                btndernier.setEnabled(true);
            }
        }
        
        txtid.setText(dt.getValueAt(i , 0).toString());
        txtnmagasin.setText(dt.getValueAt(i , 1).toString());
        txtnom.setText(dt.getValueAt(i , 2).toString());
        txtprenom.setText(dt.getValueAt(i , 3).toString());
        combservice.setSelectedItem(dt.getValueAt(i , 4).toString());
        txtduree.setText(dt.getValueAt(i , 5).toString());
        String s = dt.getValueAt(i , 6).toString();
        if(s.equals("Masculin")){jrb1.setSelected(true);}else if(s.equals("Féminin")){jrb2.setSelected(true);}
        else{jrb3.setSelected(true);}
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
    }
}

private void actualiser(){
    txtid.setText("");
        txtnom.setText("");
        txtprenom.setText("");
        combservice.setSelectedItem(1);
        jrb3.isSelected();
        txtduree.setText("");
} 

public void precedent(){
    try{
        i--;
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur avec le precedent !\n"+e.getMessage());
    }
}

public void suivant(){
    try{
        i++;
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur avec le suivant !\n"+e.getMessage());
    }
}

public void dernier(){
    try{
        i = dt.getRowCount() - 1;
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur precedent !\n"+e.getMessage());
    }
}

public void premier(){
    try{
        i=0;
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur avec le premier !\n"+e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliGDS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliGDS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliGDS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliGDS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
         Connection connexion = null;
         
        java.awt.EventQueue.invokeLater(() -> {
            new AppliGDS1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnn1;
    private javax.swing.JButton btnn2;
    private javax.swing.JButton btnn3;
    private javax.swing.JButton btnn4;
    private javax.swing.JButton btnn5;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JComboBox<String> comborech;
    private javax.swing.JComboBox<String> combservice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JCheckBox jrb1;
    private javax.swing.JCheckBox jrb2;
    private javax.swing.JCheckBox jrb3;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JTable tblstg;
    private javax.swing.JTextField txtduree;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnmagasin;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
